### PR TITLE
Social media icons

### PR DESCRIPTION
**Pull request by sodapopinsky**
If this works, we can remove passport module and auth links

### CODE REVIEW

**Comment by blakeparkinson** [comment]
Does it work? Where are the actual icons?

**Comment by sodapopinsky** [comment]
You don't see them at the index page?

**Comment by blakeparkinson** [comment]
I'm just looking at th code from my phone :troll:

**Comment by blakeparkinson** [comment]
I'm not a big fan of how these are generated in an iframe. It lessens our control of styling them ourselves. CNN's are not in an iframe but aside from that everything else looks functionally the same. Is there a way to not use the iframe?

**Pull request closed without merging**
