### PR TITLE
Adding team name to mongo + other fixes

### PR DESCRIPTION
**Pull request by blakeparkinson**

### CODE REVIEW

**Comment by kelseyedmodo** [comment]
can you make these changes on player_import too por favor?

**Comment by blakeparkinson** [comment]
u trollin? players_import uses these methods.

**Comment by kelseyedmodo** [comment]
Lol- maybe I was on wrong branch when I looked

**Comment by kelseyedmodo** [comment]
No, I still don't see the team_name line added in player_import... is that right?

**Pull request merged**
