### PR TITLE
style changes

### PR DESCRIPTION
**Pull request by HenryEdmodo**
- better button
- footer same size as header
- opacity for trending quizzes div

### CODE REVIEW

**Comment by blakeparkinson** [comment]
@HenryEdmodo you pwned yourself by self merging and now you have conflict

**Comment by HenryEdmodo** [comment]
Me to myself:
http://m.bleacherreport.com/articles/2416766-internet-reacts-to-chris-paul-getting-his-ankles-broken-by-stephen-curry?utm_source=facebook.com&utm_medium=referral&utm_campaign=programming?is_shared=true

Jk the self merge to master had nothing to do with it.

On Wednesday, April 1, 2015, Blake Parkinson <notifications@github.com>
wrote:

> @HenryEdmodo <https://github.com/HenryEdmodo> you pwned yourself by self
> merging and now you have conflict
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blakeparkinson/sports2/pull/226#issuecomment-88735285>
> .
>


-- 
*Henry Lyford*
Manager, Partnerships & Business Development
Edmodo.com/henry

**Comment by blakeparkinson** [comment]
well can u fix it?!?!?!

**Comment by HenryEdmodo** [comment]
Not sure I know how can u show me?

On Wed, Apr 1, 2015 at 10:13 PM, Blake Parkinson <notifications@github.com>
wrote:

> well can u fix it?!?!?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/blakeparkinson/sports2/pull/226#issuecomment-88737952>
> .
>



-- 
*Henry Lyford*
Manager, Partnerships & Business Development
Edmodo.com/henry

**Comment by blakeparkinson** [comment]
yay :100:

**Pull request merged**
